### ISSUE TITLE
gui warning still issued when script is deactivated

### ISSUE THREAD

**Issue by scrooloose** [godlygeek/csapprox#1]
If you run csapprox on vim where has("gui")==0 it will issue a warning, no problem. But if you run it with has("gui")==0 and CSApprox_loaded==1 then you still get the warning even though you have turned the plugin off.

Check out this commit this dude sent me for my vimfiles repo --> http://github.com/TwP/vimfiles/commit/798d124e795d4bc3b263521acafaa3d53affafc5

**Comment by godlygeek** [comment]
Fixed in cdde3b6aded5ae04c62981adc5e3129b7f5f56b2
