### ISSUE TITLE
Vim tabs are unreadable after conversion, no matter which color scheme was converted

### ISSUE THREAD

**Issue by crittermike** [godlygeek/csapprox#3]
I use vim's tabs a lot, but after converting a theme using this, the tabs are always white text on a white background. Any idea how I can get them readable? Any more info I could provide?

**Comment by crittermike** [comment]
Never mind, I finally found lines like these (https://gist.github.com/793368) and commented them out. Thanks for the great plugin!

**Comment by godlygeek** [comment]
What colorscheme caused you the problem?

**Comment by crittermike** [comment]
An example one is http://www.vim.org/scripts/script.php?script_id=2078

Is it possible my OS theme could be causing problems here? I'm using vim in a terminal, so I wouldn't think any GUI theme colors would be interacting.
