### ISSUE TITLE
FixupGuiInfo error

### ISSUE THREAD

**Issue by kurkale6ka** [godlygeek/csapprox#6]
Hi godlygeek,

As of late I am getting this error every time I start vim or try to set a colorscheme:

Error detected while processing function <SNR>20_CSApprox..<SNR>20_CSApproxImpl..<SNR>20_FixupGuiInfo:
line    1:
E716: Key not present in Dictionary: 0
E15: Invalid expression: a:highlights[s:hlid_normal].gui.bg == ''
Error detected while processing /home/mitko/config/vimfiles/bundle/csapprox/after/plugin/CSApprox.vim:
line    3:
E171: Missing :endif

Cheers

**Comment by kurkale6ka** [comment]
The problem was solved by installing gvim. I will have to check but most probably my vim binary wasn't built with gui support.

**Comment by asyncjake** [comment]
@kurkale6ka - You da MVP. I found your post due to the same error on a GalliumOS chromebook, and this answer saved my life.
