### ISSUE TITLE
error on enter

### ISSUE THREAD

**Issue by phildobbin** [godlygeek/csapprox#8]
I'm getting

`CSApprox needs gui support - not loading.
  See :help |csapprox-+gui| for possible workarounds.
Press ENTER or type command to continue`

on Fedora 14. I've had this issue before on Debian Squeeze & after following the steps in the :help referenced above, all's been fine. However, although CSApprox does its job perfectly on Fedora (i.e. console colours work great as expected) I can't get rid of the error message even though I've again followed the instructions in :help.

This is stopping me passing commands on the cli to Vim as the process is interrupted before Vim can handle the request.

Any help appreciated...

**Comment by sunaku** [comment]
If passing commands to Vim is more important than loading your vimrc, then try passing `-u NONE` to vim.  That will bypass your vimrc (and thereby csapprox) completely, ensuring that your commands are propagated.

**Comment by phildobbin** [comment]
O.K. Thanks for your help. I'll figure out a way to do it without disabling everything.

**Comment by godlygeek** [comment]
Which solution there are you trying?  Aliasing vim to gvim -v?
Symlinking gvim to vim?  What do you get if you run:

readlink -f `which gvim`

~Matt

On Sun, Mar 18, 2012 at 8:10 AM, phildobbin
reply@reply.github.com
wrote:

**Comment by phildobbin** [comment]
Hi, Matt.

The colours are working fine in console Vim on Fedora as they do in OS X & Debian with CSApprox but for some reason on Fedora I'm still getting the error message about the GUI support not loading.

I didn't need to alias or symlink on Deb or OS X but I guess I can try it on Fedora to see if it cures the error message.

**Comment by godlygeek** [comment]
At least on Debian, it's normal for the vim binary to be a symlink for
the gvim binary.  Don't know about OS X.  But that's a perfectly sane
setup, and if you have the rights to do it, then it would be a
reasonable thing to do on Fedora as well.

~Matt

On Sun, Mar 18, 2012 at 3:11 PM, phildobbin
reply@reply.github.com
wrote:

**Comment by phildobbin** [comment]
OK. I'm not in front of either of the Fedora boxes at the moment so, when I am, I'll go ahead & link them & let you know the outcome.

Thanks for your help.

**Comment by phildobbin** [comment]
I tried creating the symlink but it already existed:

`ln: creating symbolic link /usr/bin/vim: File exists`

& checking `:echo ('has gui')` returned 0 so all things considered I'm lucky CSApprox is working for me at all in the circumstances ( as I mentioned the colours are fine).

What I've done, seeing as I've all the rpms pertaining to Vim from yum & not wanting to actually uninstall it & compile from source just to get rid of one error message, is modify my bash script to allow time for Vim to catch the process.

Thanks for your help & sorry for the noise...

**Comment by godlygeek** [comment]
Save a backup of your vim binary, and then use ln -sf instead of ln -s
to overwrite the binary with a symlink to gvim

On Tue, Mar 20, 2012 at 10:03 AM, phildobbin
reply@reply.github.com
wrote:

**Comment by phildobbin** [comment]
Thanks, Matt, I'll bear that in mind.

Don't think at the moment though, I'll do it 'cause I've already downloaded the source code
from Mercurial for Vim & I think, having gathered up all the relevant dev/header files,
I'll compile my own Vim as I did for OS X.

Many thanks for all your help...
